# Generated by Django 5.0.7 on 2024-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
