# Generated by Django 5.0.7 on 2024-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='valid_time',
            field=models.DateField(),
        ),
    ]
