# Generated by Django 5.0.7 on 2024-09-17 11:12

import story.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_valid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='resource',
            field=models.FileField(upload_to='story/', validators=[story.validator.validate_file_extension]),
        ),
    ]
