# Generated by Django 5.0.7 on 2024-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
