# Generated by Django 5.0.7 on 2024-10-07 12:40

import django.db.models.deletion
import story.validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_story_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(upload_to='story/', validators=[story.validator.validate_file_extension])),
                ('is_valid', models.BooleanField(default=True)),
                ('valid_time', models.DateField()),
                ('text', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended', to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
