# Generated by Django 5.0.7 on 2024-10-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_extendedstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedstory',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='extendedstory',
            name='valid_time',
        ),
        migrations.RemoveField(
            model_name='story',
            name='valid_time',
        ),
    ]
